-- 024_candidate_verification.sql
--
-- Two problems this fixes:
--
-- 1. candidates.status had drifted off-vocabulary. The app's canonical set is
--    ('running','withdrawn','won','lost') -- see lib/validations/admin.ts and
--    components/admin/candidate-form.tsx -- but 531 rows stored 'active', which
--    is in none of them. Consequences: STATUS_CONFIG lookups silently fell
--    through to the 'running' fallback, candidateSchema rejected the value on
--    any admin save, and the admin <select> defaultValue matched no <option>
--    (so opening the form pre-selected the wrong status and saving rewrote it).
--    Normalized here, then locked with a CHECK so it cannot drift again.
--
-- 2. No way to tell a hand-verified candidate from one auto-generated by a seed
--    script. The 2026 roster was machine-generated on the assumption that every
--    incumbent seeks reelection, which is false for retirements, members running
--    for another office, and primary losers. is_verified/last_checked let the
--    unverified rows be identified and worked through against a real source.
--
-- Idempotent -- safe to re-run.

-- 1. provenance columns
alter table candidates add column if not exists is_verified boolean not null default false;
alter table candidates add column if not exists last_checked timestamptz;

comment on column candidates.is_verified is
  'True only when this candidacy was confirmed against an authoritative source (state SoS filing, FEC, AP). Seed-generated rows are false.';
comment on column candidates.last_checked is
  'When this candidacy was last confirmed against an authoritative source.';

-- 2. normalize the off-vocabulary status before constraining it
update candidates set status = 'running' where status = 'active';

-- 3. lock the vocabulary
alter table candidates drop constraint if exists candidates_status_check;
alter table candidates
  add constraint candidates_status_check
  check (status in ('running', 'withdrawn', 'won', 'lost'));

-- 4. find unverified rows quickly
create index if not exists candidates_is_verified_idx on candidates (is_verified);
