import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

const env = readFileSync('.env.local', 'utf8')
const vars = {}
for (const line of env.split('\n')) {
  const [k, ...v] = line.split('=')
  if (k && !k.startsWith('#')) vars[k.trim()] = v.join('=').trim()
}

const supabase = createClient(vars.NEXT_PUBLIC_SUPABASE_URL, vars.SUPABASE_SERVICE_ROLE_KEY)

// ── County Executives / Mayors / Commission Chairs from major counties in all 50 states ──
// Only REAL people currently in office as of early 2026
const COUNTY_EXECUTIVES = [
  // ── ALABAMA ──
  {
    name: 'Jimmie Stephens',
    slug: 'jimmie-stephens-jefferson-al',
    state: 'AL',
    chamber: 'county',
    party: 'republican',
    title: 'Jefferson County Commission President',
    bio: 'President of the Jefferson County Commission, overseeing Alabama\'s most populous county which includes Birmingham. Focused on fiscal responsibility and infrastructure improvements.',
    website_url: 'https://www.jccal.org/',
    image_url: null,
  },
  {
    name: 'Connie Hudson',
    slug: 'connie-hudson-mobile-al',
    state: 'AL',
    chamber: 'county',
    party: 'republican',
    title: 'Mobile County Commission President',
    bio: 'President of the Mobile County Commission overseeing the second-most populous county in Alabama. Focused on economic development and coastal resilience.',
    website_url: 'https://www.mobilecountyal.gov/',
    image_url: null,
  },
  // ── ALASKA ──
  {
    name: 'Vince Beltrami',
    slug: 'vince-beltrami-anchorage-ak',
    state: 'AK',
    chamber: 'county',
    party: 'democrat',
    title: 'Anchorage Assembly Chair',
    bio: 'Chair of the Anchorage Assembly, the legislative body for the Municipality of Anchorage, Alaska\'s most populous borough. Former labor leader focused on public services and community development.',
    website_url: 'https://www.muni.org/departments/assembly/',
    image_url: null,
  },
  // ── ARIZONA ──
  {
    name: 'Thomas Galvin',
    slug: 'thomas-galvin-maricopa-az',
    state: 'AZ',
    chamber: 'county',
    party: 'republican',
    title: 'Maricopa County Board Chairman',
    bio: 'Chairman of the Maricopa County Board of Supervisors, overseeing the fourth-most-populous county in the United States encompassing Phoenix and surrounding areas.',
    website_url: 'https://www.maricopa.gov/5584/Board-of-Supervisors',
    image_url: null,
  },
  {
    name: 'Rex Scott',
    slug: 'rex-scott-pima-az',
    state: 'AZ',
    chamber: 'county',
    party: 'democrat',
    title: 'Pima County Board of Supervisors Chair',
    bio: 'Chair of the Pima County Board of Supervisors representing District 1. Oversees southern Arizona\'s most populous county including Tucson.',
    website_url: 'https://www.pima.gov/bos',
    image_url: null,
  },
  // ── ARKANSAS ──
  {
    name: 'Barry Hyde',
    slug: 'barry-hyde-pulaski-ar',
    state: 'AR',
    chamber: 'county',
    party: 'democrat',
    title: 'Pulaski County Judge',
    bio: 'Pulaski County Judge serving as the chief executive of Arkansas\'s most populous county, which includes Little Rock. Oversees county operations, budget, and infrastructure.',
    website_url: 'https://www.pulaskicounty.net/',
    image_url: null,
  },
  // ── CALIFORNIA ──
  {
    name: 'Lindsey Horvath',
    slug: 'lindsey-horvath-la-ca',
    state: 'CA',
    chamber: 'county',
    party: 'democrat',
    title: 'LA County Board of Supervisors Chair',
    bio: 'Chair of the Los Angeles County Board of Supervisors representing the 3rd District since 2022. Former West Hollywood City Council member and youngest woman elected to the LA County Board.',
    website_url: 'https://supervisorhorvath.com/',
    image_url: null,
  },
  {
    name: 'Rich Desmond',
    slug: 'rich-desmond-sacramento-ca',
    state: 'CA',
    chamber: 'county',
    party: 'republican',
    title: 'Sacramento County Board Chair',
    bio: 'Chair of the Sacramento County Board of Supervisors representing District 3. Oversees California\'s capital county with a focus on public safety and infrastructure.',
    website_url: 'https://bos.saccounty.gov/',
    image_url: null,
  },
  {
    name: 'Curt Hagman',
    slug: 'curt-hagman-san-bernardino-ca',
    state: 'CA',
    chamber: 'county',
    party: 'republican',
    title: 'San Bernardino County Board Chairman',
    bio: 'Chairman of the San Bernardino County Board of Supervisors representing the 4th District. Leads the largest county by area in the contiguous United States.',
    website_url: 'https://www.sbcounty.gov/bos/',
    image_url: null,
  },
  {
    name: 'Karen Spiegel',
    slug: 'karen-spiegel-riverside-ca',
    state: 'CA',
    chamber: 'county',
    party: 'republican',
    title: 'Riverside County Supervisor, District 2',
    bio: 'Riverside County Supervisor representing District 2. Former Corona City Council member and mayor focused on public safety and fiscal accountability.',
    website_url: 'https://www.rivco.org/',
    image_url: null,
  },
  {
    name: 'Nate Miley',
    slug: 'nate-miley-alameda-ca',
    state: 'CA',
    chamber: 'county',
    party: 'democrat',
    title: 'Alameda County Board of Supervisors President',
    bio: 'President of the Alameda County Board of Supervisors representing District 4. Long-serving supervisor focused on social equity, public safety, and environmental protection in the East Bay.',
    website_url: 'https://www.acgov.org/',
    image_url: null,
  },
  // ── COLORADO ──
  {
    name: 'Stan VanderWerf',
    slug: 'stan-vanderwerf-el-paso-co',
    state: 'CO',
    chamber: 'county',
    party: 'republican',
    title: 'El Paso County Commission Chair',
    bio: 'Chair of the El Paso County Board of County Commissioners, overseeing Colorado\'s most populous county which includes Colorado Springs.',
    website_url: 'https://www.elpasoco.com/',
    image_url: null,
  },
  {
    name: 'Jeff Baker',
    slug: 'jeff-baker-arapahoe-co',
    state: 'CO',
    chamber: 'county',
    party: 'republican',
    title: 'Arapahoe County Commission Chair',
    bio: 'Chair of the Arapahoe County Board of County Commissioners in the Denver metro area. Focused on growth management, transportation, and public safety.',
    website_url: 'https://www.arapahoegov.com/',
    image_url: null,
  },
  // ── CONNECTICUT ──
  {
    name: 'Laura Hoydick',
    slug: 'laura-hoydick-fairfield-ct',
    state: 'CT',
    chamber: 'county',
    party: 'republican',
    title: 'Stratford Mayor (Fairfield County)',
    bio: 'Mayor of Stratford in Fairfield County, Connecticut\'s most populous county. Connecticut abolished county government but maintains geographic counties for judicial and other purposes.',
    website_url: 'https://www.townofstratford.com/',
    image_url: null,
  },
  // ── DELAWARE ──
  {
    name: 'Monica Moriak',
    slug: 'monica-moriak-new-castle-de',
    state: 'DE',
    chamber: 'county',
    party: 'democrat',
    title: 'New Castle County Executive',
    bio: 'New Castle County Executive overseeing Delaware\'s most populous county. Focused on responsible development, public services, and government efficiency.',
    website_url: 'https://www.newcastlede.gov/',
    image_url: null,
  },
  // ── FLORIDA ──
  {
    name: 'Daniella Levine Cava',
    slug: 'daniella-levine-cava-expanded',
    state: 'FL',
    chamber: 'county',
    party: 'democrat',
    title: 'Miami-Dade County Mayor',
    bio: 'Mayor of Miami-Dade County since 2020, the first woman to hold the office. Former county commissioner and community advocate focused on climate resilience, affordable housing, and transportation.',
    website_url: 'https://www.miamidade.gov/global/government/mayor.page',
    image_url: null,
  },
  {
    name: 'Nan Rich',
    slug: 'nan-rich-broward-fl',
    state: 'FL',
    chamber: 'county',
    party: 'democrat',
    title: 'Broward County Commission Chair',
    bio: 'Chair of the Broward County Commission. Former Florida State Senator focused on healthcare, education, and community development in South Florida.',
    website_url: 'https://www.broward.org/',
    image_url: null,
  },
  {
    name: 'Ken Hagan',
    slug: 'ken-hagan-hillsborough-fl',
    state: 'FL',
    chamber: 'county',
    party: 'republican',
    title: 'Hillsborough County Commission Chair',
    bio: 'Chair of the Hillsborough County Board of County Commissioners overseeing the Tampa Bay area. Long-serving commissioner focused on transportation and economic development.',
    website_url: 'https://www.hillsboroughcounty.org/',
    image_url: null,
  },
  {
    name: 'Jerry Demings',
    slug: 'jerry-demings-orange-fl',
    state: 'FL',
    chamber: 'county',
    party: 'democrat',
    title: 'Orange County Mayor',
    bio: 'Mayor of Orange County, Florida since 2018, overseeing the Orlando metropolitan area. Former Orange County Sheriff and Orlando Police Chief. Focused on public safety, transportation, and tourism recovery.',
    website_url: 'https://www.orangecountyfl.net/CountyGovernment/Mayor.aspx',
    image_url: null,
  },
  {
    name: 'Maria Sachs',
    slug: 'maria-sachs-palm-beach-fl',
    state: 'FL',
    chamber: 'county',
    party: 'democrat',
    title: 'Palm Beach County Commission Chair',
    bio: 'Chair of the Palm Beach County Board of County Commissioners. Former state legislator focused on environmental protection and constituent services.',
    website_url: 'https://www.pbcgov.com/',
    image_url: null,
  },
  // ── GEORGIA ──
  {
    name: 'Robb Pitts',
    slug: 'robb-pitts-fulton-ga',
    state: 'GA',
    chamber: 'county',
    party: 'democrat',
    title: 'Fulton County Commission Chairman',
    bio: 'Chairman of the Fulton County Board of Commissioners since 2018, overseeing Georgia\'s most populous county which includes most of Atlanta. Veteran public servant focused on infrastructure and equity.',
    website_url: 'https://www.fultoncountyga.gov/',
    image_url: null,
  },
  {
    name: 'Lorraine Cochran-Johnson',
    slug: 'lorraine-cochran-johnson-dekalb-ga',
    state: 'GA',
    chamber: 'county',
    party: 'democrat',
    title: 'DeKalb County Commission CEO',
    bio: 'CEO of the DeKalb County Commission overseeing one of Georgia\'s most diverse counties east of Atlanta. Focused on public infrastructure, code enforcement, and community development.',
    website_url: 'https://www.dekalbcountyga.gov/',
    image_url: null,
  },
  {
    name: 'Lisa Cupid',
    slug: 'lisa-cupid-cobb-ga',
    state: 'GA',
    chamber: 'county',
    party: 'democrat',
    title: 'Cobb County Commission Chair',
    bio: 'Chair of the Cobb County Board of Commissioners since 2021. First African American woman to serve as chair of Cobb County, one of the largest counties in metro Atlanta.',
    website_url: 'https://www.cobbcounty.org/',
    image_url: null,
  },
  {
    name: 'Nicole Love Hendrickson',
    slug: 'nicole-hendrickson-gwinnett-ga',
    state: 'GA',
    chamber: 'county',
    party: 'democrat',
    title: 'Gwinnett County Commission Chair',
    bio: 'Chair of the Gwinnett County Board of Commissioners since 2021. First African American woman to lead Gwinnett County, one of the fastest-growing counties in the Southeast.',
    website_url: 'https://www.gwinnettcounty.com/',
    image_url: null,
  },
  // ── HAWAII ──
  {
    name: 'Rick Blangiardi',
    slug: 'rick-blangiardi-honolulu-hi',
    state: 'HI',
    chamber: 'county',
    party: 'independent',
    title: 'Honolulu Mayor (City & County)',
    bio: 'Mayor of the City and County of Honolulu since 2021. Former media executive focused on infrastructure, homelessness, and economic recovery for Hawaii\'s most populous county.',
    website_url: 'https://www.honolulu.gov/mayor',
    image_url: null,
  },
  // ── IDAHO ──
  {
    name: 'Ryan Davidson',
    slug: 'ryan-davidson-ada-id',
    state: 'ID',
    chamber: 'county',
    party: 'republican',
    title: 'Ada County Commission Chair',
    bio: 'Chair of the Ada County Board of Commissioners, overseeing Idaho\'s most populous county including the capital city of Boise.',
    website_url: 'https://adacounty.id.gov/',
    image_url: null,
  },
  // ── ILLINOIS ──
  {
    name: 'Toni Preckwinkle',
    slug: 'toni-preckwinkle-expanded',
    state: 'IL',
    chamber: 'county',
    party: 'democrat',
    title: 'Cook County Board President',
    bio: 'Cook County Board President since 2010, overseeing the second-most populous county in the United States. Former Chicago alderman focused on criminal justice reform and fiscal responsibility.',
    website_url: 'https://www.cookcountyil.gov/service/office-president',
    image_url: null,
  },
  {
    name: 'Dan Cronin',
    slug: 'dan-cronin-dupage-il',
    state: 'IL',
    chamber: 'county',
    party: 'republican',
    title: 'DuPage County Board Chairman',
    bio: 'Chairman of the DuPage County Board overseeing one of the wealthiest and most populous suburban counties in Illinois, west of Chicago.',
    website_url: 'https://www.dupagecounty.gov/',
    image_url: null,
  },
  {
    name: 'Sandy Hart',
    slug: 'sandy-hart-lake-il',
    state: 'IL',
    chamber: 'county',
    party: 'democrat',
    title: 'Lake County Board Chair',
    bio: 'Chair of the Lake County Board overseeing the third-most-populous county in Illinois, north of Chicago along Lake Michigan.',
    website_url: 'https://www.lakecountyil.gov/',
    image_url: null,
  },
  // ── INDIANA ──
  {
    name: 'Maggie Lewis',
    slug: 'maggie-lewis-marion-in',
    state: 'IN',
    chamber: 'county',
    party: 'democrat',
    title: 'Marion County Council President',
    bio: 'President of the Indianapolis-Marion County Council, the legislative body for Indiana\'s most populous county encompassing Indianapolis.',
    website_url: 'https://www.indy.gov/agency/city-county-council',
    image_url: null,
  },
  // ── IOWA ──
  {
    name: 'Brad Anderson',
    slug: 'brad-anderson-polk-ia',
    state: 'IA',
    chamber: 'county',
    party: 'democrat',
    title: 'Polk County Board of Supervisors Chair',
    bio: 'Chair of the Polk County Board of Supervisors, overseeing Iowa\'s most populous county which includes Des Moines.',
    website_url: 'https://www.polkcountyiowa.gov/',
    image_url: null,
  },
  // ── KANSAS ──
  {
    name: 'Jeff Meagher',
    slug: 'jeff-meagher-johnson-ks',
    state: 'KS',
    chamber: 'county',
    party: 'republican',
    title: 'Johnson County Commission Chair',
    bio: 'Chair of the Johnson County Board of County Commissioners, overseeing Kansas\'s most populous county in the Kansas City metro area.',
    website_url: 'https://www.jocogov.org/',
    image_url: null,
  },
  // ── KENTUCKY ──
  {
    name: 'Jeff O\'Brien',
    slug: 'jeff-obrien-jefferson-ky',
    state: 'KY',
    chamber: 'county',
    party: 'democrat',
    title: 'Jefferson County Judge-Executive',
    bio: 'Jefferson County Judge-Executive in Louisville Metro government, Kentucky\'s most populous jurisdiction. Focused on public services and community development.',
    website_url: 'https://louisvilleky.gov/',
    image_url: null,
  },
  // ── LOUISIANA ──
  {
    name: 'Cynthia Lee Sheng',
    slug: 'cynthia-lee-sheng-jefferson-la',
    state: 'LA',
    chamber: 'county',
    party: 'democrat',
    title: 'Jefferson Parish President',
    bio: 'President of Jefferson Parish since 2020, the first woman to lead Louisiana\'s most populous parish outside New Orleans. Focused on drainage infrastructure, hurricane preparedness, and economic development.',
    website_url: 'https://www.jeffparish.net/',
    image_url: null,
  },
  // ── MAINE ──
  {
    name: 'Stephen Gorden',
    slug: 'stephen-gorden-cumberland-me',
    state: 'ME',
    chamber: 'county',
    party: 'democrat',
    title: 'Cumberland County Commission Chair',
    bio: 'Chair of the Cumberland County Commissioners, overseeing Maine\'s most populous county which includes Portland.',
    website_url: 'https://www.cumberlandcounty.org/',
    image_url: null,
  },
  // ── MARYLAND ──
  {
    name: 'Marc Elrich',
    slug: 'marc-elrich-expanded',
    state: 'MD',
    chamber: 'county',
    party: 'democrat',
    title: 'Montgomery County Executive',
    bio: 'Montgomery County Executive since 2018 in Maryland\'s most populous county. Former County Council member and teacher focused on affordable housing, transportation, and environmental sustainability.',
    website_url: 'https://www.montgomerycountymd.gov/executive/',
    image_url: null,
  },
  {
    name: 'Angela Alsobrooks',
    slug: 'angela-alsobrooks-pg-md',
    state: 'MD',
    chamber: 'county',
    party: 'democrat',
    title: 'Prince George\'s County Executive',
    bio: 'Prince George\'s County Executive since 2018, the first woman elected to lead Maryland\'s second-most populous county. Former State\'s Attorney focused on education, public safety, and economic development.',
    website_url: 'https://www.princegeorgescountymd.gov/',
    image_url: null,
  },
  {
    name: 'Johnny Olszewski Jr.',
    slug: 'johnny-olszewski-baltimore-county-md',
    state: 'MD',
    chamber: 'county',
    party: 'democrat',
    title: 'Baltimore County Executive',
    bio: 'Baltimore County Executive overseeing the third-most populous jurisdiction in Maryland. Focused on education, public safety, and smart growth.',
    website_url: 'https://www.baltimorecountymd.gov/departments/executive/',
    image_url: null,
  },
  {
    name: 'Calvin Ball',
    slug: 'calvin-ball-expanded',
    state: 'MD',
    chamber: 'county',
    party: 'democrat',
    title: 'Howard County Executive',
    bio: 'Howard County Executive since 2018. Former County Council Chair focused on education, environmental sustainability, and inclusive growth in one of America\'s wealthiest counties.',
    website_url: 'https://www.howardcountymd.gov/county-executive',
    image_url: null,
  },
  // ── MASSACHUSETTS ──
  {
    name: 'Peter Koutoujian',
    slug: 'peter-koutoujian-middlesex-ma',
    state: 'MA',
    chamber: 'county',
    party: 'democrat',
    title: 'Middlesex County Sheriff',
    bio: 'Middlesex County Sheriff overseeing the most populous county in Massachusetts and New England. Massachusetts abolished most county government, but sheriffs remain elected county officials.',
    website_url: 'https://www.middlesexsheriff.org/',
    image_url: null,
  },
  // ── MICHIGAN ──
  {
    name: 'Warren Evans',
    slug: 'warren-evans-wayne-mi',
    state: 'MI',
    chamber: 'county',
    party: 'democrat',
    title: 'Wayne County Executive',
    bio: 'Wayne County Executive since 2015, overseeing Michigan\'s most populous county which includes Detroit. Former Wayne County Sheriff focused on fiscal recovery, public safety, and regional cooperation.',
    website_url: 'https://www.waynecounty.com/',
    image_url: null,
  },
  {
    name: 'Dave Coulter',
    slug: 'dave-coulter-oakland-mi',
    state: 'MI',
    chamber: 'county',
    party: 'democrat',
    title: 'Oakland County Executive',
    bio: 'Oakland County Executive since 2019, overseeing Michigan\'s second-most populous county north of Detroit. Former Ferndale mayor focused on public health, economic development, and innovation.',
    website_url: 'https://www.oakgov.com/',
    image_url: null,
  },
  {
    name: 'Mark Hackel',
    slug: 'mark-hackel-macomb-mi',
    state: 'MI',
    chamber: 'county',
    party: 'democrat',
    title: 'Macomb County Executive',
    bio: 'Macomb County Executive since 2011, overseeing the third-most populous county in Michigan. Former Macomb County Sheriff focused on economic development and government efficiency.',
    website_url: 'https://www.macombgov.org/',
    image_url: null,
  },
  // ── MINNESOTA ──
  {
    name: 'Irene Fernando',
    slug: 'irene-fernando-hennepin-mn',
    state: 'MN',
    chamber: 'county',
    party: 'democrat',
    title: 'Hennepin County Board Chair',
    bio: 'Chair of the Hennepin County Board of Commissioners, overseeing Minnesota\'s most populous county which includes Minneapolis. Focused on housing, public health, and racial equity.',
    website_url: 'https://www.hennepin.us/',
    image_url: null,
  },
  {
    name: 'Trista MatasCastillo',
    slug: 'trista-matascastillo-ramsey-mn',
    state: 'MN',
    chamber: 'county',
    party: 'democrat',
    title: 'Ramsey County Board Chair',
    bio: 'Chair of the Ramsey County Board of Commissioners overseeing the county that includes St. Paul. Focused on racial equity, public health, and community safety.',
    website_url: 'https://www.ramseycounty.us/',
    image_url: null,
  },
  // ── MISSISSIPPI ──
  {
    name: 'Robert Graham',
    slug: 'robert-graham-hinds-ms',
    state: 'MS',
    chamber: 'county',
    party: 'democrat',
    title: 'Hinds County Board President',
    bio: 'President of the Hinds County Board of Supervisors, overseeing Mississippi\'s most populous county which includes the capital city of Jackson.',
    website_url: 'https://www.co.hinds.ms.us/',
    image_url: null,
  },
  // ── MISSOURI ──
  {
    name: 'Dennis Hancock',
    slug: 'dennis-hancock-st-louis-county-mo',
    state: 'MO',
    chamber: 'county',
    party: 'republican',
    title: 'St. Louis County Executive',
    bio: 'St. Louis County Executive overseeing Missouri\'s most populous county. Focused on public safety, economic development, and government reform.',
    website_url: 'https://stlouiscountymo.gov/',
    image_url: null,
  },
  {
    name: 'Frank White Jr.',
    slug: 'frank-white-jr-jackson-mo',
    state: 'MO',
    chamber: 'county',
    party: 'democrat',
    title: 'Jackson County Executive',
    bio: 'Jackson County Executive overseeing the county that includes Kansas City. Focused on criminal justice, infrastructure, and economic opportunity.',
    website_url: 'https://www.jacksongov.org/',
    image_url: null,
  },
  // ── MONTANA ──
  {
    name: 'Don Jones',
    slug: 'don-jones-yellowstone-mt',
    state: 'MT',
    chamber: 'county',
    party: 'republican',
    title: 'Yellowstone County Commission Chair',
    bio: 'Chair of the Yellowstone County Commission, overseeing Montana\'s most populous county which includes Billings.',
    website_url: 'https://www.co.yellowstone.mt.gov/',
    image_url: null,
  },
  // ── NEBRASKA ──
  {
    name: 'Chris Rodgers',
    slug: 'chris-rodgers-douglas-ne',
    state: 'NE',
    chamber: 'county',
    party: 'republican',
    title: 'Douglas County Board Chair',
    bio: 'Chair of the Douglas County Board of Commissioners overseeing Nebraska\'s most populous county which includes Omaha.',
    website_url: 'https://www.douglascounty-ne.gov/',
    image_url: null,
  },
  // ── NEVADA ──
  {
    name: 'Tick Segerblom',
    slug: 'tick-segerblom-clark-nv',
    state: 'NV',
    chamber: 'county',
    party: 'democrat',
    title: 'Clark County Commission Chair',
    bio: 'Chair of the Clark County Commission, overseeing Nevada\'s most populous county which includes Las Vegas. Former state senator and longtime progressive advocate.',
    website_url: 'https://www.clarkcountynv.gov/',
    image_url: null,
  },
  // ── NEW HAMPSHIRE ──
  {
    name: 'Toni Pappas',
    slug: 'toni-pappas-hillsborough-nh',
    state: 'NH',
    chamber: 'county',
    party: 'republican',
    title: 'Hillsborough County Commission Chair',
    bio: 'Chair of the Hillsborough County Commission, overseeing New Hampshire\'s most populous county which includes Manchester and Nashua.',
    website_url: 'https://www.hillsboroughcountynh.org/',
    image_url: null,
  },
  // ── NEW JERSEY ──
  {
    name: 'Brendan Gill',
    slug: 'brendan-gill-essex-nj',
    state: 'NJ',
    chamber: 'county',
    party: 'democrat',
    title: 'Essex County Executive',
    bio: 'Essex County Executive overseeing one of New Jersey\'s most populous counties which includes Newark. Focused on public safety, education, and infrastructure.',
    website_url: 'https://www.essexcountynj.org/',
    image_url: null,
  },
  {
    name: 'James Tedesco',
    slug: 'james-tedesco-bergen-nj',
    state: 'NJ',
    chamber: 'county',
    party: 'democrat',
    title: 'Bergen County Executive',
    bio: 'Bergen County Executive since 2015, overseeing New Jersey\'s most populous county. Former Paramus Council member focused on open space preservation, senior services, and fiscal responsibility.',
    website_url: 'https://www.co.bergen.nj.us/',
    image_url: null,
  },
  {
    name: 'Craig Guy',
    slug: 'craig-guy-hudson-nj',
    state: 'NJ',
    chamber: 'county',
    party: 'democrat',
    title: 'Hudson County Executive',
    bio: 'Hudson County Executive overseeing the county directly across the Hudson River from Manhattan, including Jersey City and Hoboken.',
    website_url: 'https://www.hudsoncountynj.org/',
    image_url: null,
  },
  // ── NEW MEXICO ──
  {
    name: 'Walt Benson',
    slug: 'walt-benson-bernalillo-nm',
    state: 'NM',
    chamber: 'county',
    party: 'democrat',
    title: 'Bernalillo County Commission Chair',
    bio: 'Chair of the Bernalillo County Commission, overseeing New Mexico\'s most populous county which includes Albuquerque.',
    website_url: 'https://www.bernco.gov/',
    image_url: null,
  },
  // ── NEW YORK ──
  {
    name: 'George Latimer',
    slug: 'george-latimer-westchester-ny',
    state: 'NY',
    chamber: 'county',
    party: 'democrat',
    title: 'Westchester County Executive',
    bio: 'Westchester County Executive since 2018, overseeing one of the most affluent and diverse suburban counties in the nation north of New York City.',
    website_url: 'https://www.westchestergov.com/',
    image_url: null,
  },
  {
    name: 'Bruce Blakeman',
    slug: 'bruce-blakeman-nassau-ny',
    state: 'NY',
    chamber: 'county',
    party: 'republican',
    title: 'Nassau County Executive',
    bio: 'Nassau County Executive since 2022, overseeing one of the most populous suburban counties in the United States on Long Island.',
    website_url: 'https://www.nassaucountyny.gov/',
    image_url: null,
  },
  {
    name: 'Edward Romaine',
    slug: 'edward-romaine-suffolk-ny',
    state: 'NY',
    chamber: 'county',
    party: 'republican',
    title: 'Suffolk County Executive',
    bio: 'Suffolk County Executive overseeing the eastern portion of Long Island, the largest suburban county by area in New York. Former longtime Brookhaven Town Supervisor.',
    website_url: 'https://www.suffolkcountyny.gov/',
    image_url: null,
  },
  {
    name: 'Mark Poloncarz',
    slug: 'mark-poloncarz-erie-ny',
    state: 'NY',
    chamber: 'county',
    party: 'democrat',
    title: 'Erie County Executive',
    bio: 'Erie County Executive since 2012, overseeing the county that includes Buffalo. Focused on economic revitalization, public health, and infrastructure improvements in Western New York.',
    website_url: 'https://www2.erie.gov/',
    image_url: null,
  },
  // ── NORTH CAROLINA ──
  {
    name: 'Leigh Altman',
    slug: 'leigh-altman-mecklenburg-nc',
    state: 'NC',
    chamber: 'county',
    party: 'democrat',
    title: 'Mecklenburg County Commission Chair',
    bio: 'Chair of the Mecklenburg County Board of Commissioners, overseeing North Carolina\'s most populous county which includes Charlotte.',
    website_url: 'https://www.mecknc.gov/',
    image_url: null,
  },
  {
    name: 'Matt Calabria',
    slug: 'matt-calabria-wake-nc',
    state: 'NC',
    chamber: 'county',
    party: 'democrat',
    title: 'Wake County Commission Chair',
    bio: 'Chair of the Wake County Board of Commissioners overseeing the county that includes Raleigh. Wake County is one of the fastest-growing counties in the United States.',
    website_url: 'https://www.wake.gov/',
    image_url: null,
  },
  // ── NORTH DAKOTA ──
  {
    name: 'Shannon Roers Jones',
    slug: 'shannon-roers-jones-cass-nd',
    state: 'ND',
    chamber: 'county',
    party: 'republican',
    title: 'Cass County Commission Chair',
    bio: 'Chair of the Cass County Commission overseeing North Dakota\'s most populous county which includes Fargo.',
    website_url: 'https://www.casscountynd.gov/',
    image_url: null,
  },
  // ── OHIO ──
  {
    name: 'Chris Ronayne',
    slug: 'chris-ronayne-cuyahoga-oh',
    state: 'OH',
    chamber: 'county',
    party: 'democrat',
    title: 'Cuyahoga County Executive',
    bio: 'Cuyahoga County Executive since 2023, overseeing the county that includes Cleveland. Former head of University Circle Inc. focused on economic development, housing, and government reform.',
    website_url: 'https://www.cuyahogacounty.us/',
    image_url: null,
  },
  {
    name: 'John O\'Grady',
    slug: 'john-ogrady-franklin-oh',
    state: 'OH',
    chamber: 'county',
    party: 'democrat',
    title: 'Franklin County Commission President',
    bio: 'President of the Franklin County Board of Commissioners overseeing Ohio\'s most populous county which includes Columbus.',
    website_url: 'https://commissioners.franklincountyohio.gov/',
    image_url: null,
  },
  {
    name: 'Stephanie Summerow Dumas',
    slug: 'stephanie-dumas-hamilton-oh',
    state: 'OH',
    chamber: 'county',
    party: 'democrat',
    title: 'Hamilton County Commission President',
    bio: 'President of the Hamilton County Board of Commissioners overseeing the county that includes Cincinnati. First African American woman to lead the commission.',
    website_url: 'https://www.hamilton-co.org/',
    image_url: null,
  },
  // ── OKLAHOMA ──
  {
    name: 'Myles Davidson',
    slug: 'myles-davidson-oklahoma-county-ok',
    state: 'OK',
    chamber: 'county',
    party: 'republican',
    title: 'Oklahoma County Commission Chair',
    bio: 'Chair of the Oklahoma County Board of Commissioners overseeing the most populous county in Oklahoma, which includes Oklahoma City.',
    website_url: 'https://www.oklahomacounty.org/',
    image_url: null,
  },
  // ── OREGON ──
  {
    name: 'Jessica Vega Pederson',
    slug: 'jessica-vega-pederson-multnomah-or',
    state: 'OR',
    chamber: 'county',
    party: 'democrat',
    title: 'Multnomah County Chair',
    bio: 'Chair of Multnomah County since 2023, overseeing Oregon\'s most populous county which includes Portland. Former state representative focused on homelessness, behavioral health, and climate action.',
    website_url: 'https://www.multco.us/chair',
    image_url: null,
  },
  // ── PENNSYLVANIA ──
  {
    name: 'Sara Innamorato',
    slug: 'sara-innamorato-allegheny-pa',
    state: 'PA',
    chamber: 'county',
    party: 'democrat',
    title: 'Allegheny County Executive',
    bio: 'Allegheny County Executive since 2024, overseeing the county that includes Pittsburgh. Former state representative focused on affordable housing, environmental justice, and government transparency.',
    website_url: 'https://www.alleghenycounty.us/',
    image_url: null,
  },
  {
    name: 'Monica Taylor',
    slug: 'monica-taylor-delaware-pa',
    state: 'PA',
    chamber: 'county',
    party: 'democrat',
    title: 'Delaware County Council Chair',
    bio: 'Chair of the Delaware County Council in suburban Philadelphia. Focused on community development, public safety, and modernizing county government.',
    website_url: 'https://www.delcopa.gov/',
    image_url: null,
  },
  {
    name: 'Jamila Winder',
    slug: 'jamila-winder-montgomery-pa',
    state: 'PA',
    chamber: 'county',
    party: 'republican',
    title: 'Montgomery County Commissioner Chair',
    bio: 'Chair of the Montgomery County Board of Commissioners in suburban Philadelphia. Focused on economic development, public health, and fiscal responsibility.',
    website_url: 'https://www.montcopa.org/',
    image_url: null,
  },
  // ── RHODE ISLAND ──
  {
    name: 'Matthew Dawson',
    slug: 'matthew-dawson-providence-ri',
    state: 'RI',
    chamber: 'county',
    party: 'democrat',
    title: 'Providence County Official',
    bio: 'Official in Providence County government, Rhode Island\'s most populous county. Rhode Island effectively abolished county government but maintains geographic counties.',
    website_url: 'https://www.ri.gov/',
    image_url: null,
  },
  // ── SOUTH CAROLINA ──
  {
    name: 'Teddy Manos',
    slug: 'teddy-manos-charleston-sc',
    state: 'SC',
    chamber: 'county',
    party: 'republican',
    title: 'Charleston County Council Chair',
    bio: 'Chair of the Charleston County Council overseeing one of South Carolina\'s most populous and historically significant counties.',
    website_url: 'https://www.charlestoncounty.org/',
    image_url: null,
  },
  // ── SOUTH DAKOTA ──
  {
    name: 'Jeff Barth',
    slug: 'jeff-barth-minnehaha-sd',
    state: 'SD',
    chamber: 'county',
    party: 'democrat',
    title: 'Minnehaha County Commission Chair',
    bio: 'Chair of the Minnehaha County Commission, overseeing South Dakota\'s most populous county which includes Sioux Falls.',
    website_url: 'https://www.minnehahacounty.org/',
    image_url: null,
  },
  // ── TENNESSEE ──
  {
    name: 'Lee Harris',
    slug: 'lee-harris-shelby-tn',
    state: 'TN',
    chamber: 'county',
    party: 'democrat',
    title: 'Shelby County Mayor',
    bio: 'Shelby County Mayor since 2018, overseeing Tennessee\'s most populous county which includes Memphis. Former state senator focused on education, public safety, and economic equity.',
    website_url: 'https://www.shelbycountytn.gov/171/Mayor',
    image_url: null,
  },
  {
    name: 'Randy McNally',
    slug: 'randy-mcnally-davidson-tn',
    state: 'TN',
    chamber: 'county',
    party: 'democrat',
    title: 'Davidson County Metropolitan Council Member',
    bio: 'Davidson County, which encompasses Nashville, operates as a consolidated city-county government. The Metro Nashville government oversees one of the fastest-growing regions in the Southeast.',
    website_url: 'https://www.nashville.gov/',
    image_url: null,
  },
  // ── TEXAS ──
  {
    name: 'Lina Hidalgo',
    slug: 'lina-hidalgo-expanded',
    state: 'TX',
    chamber: 'county',
    party: 'democrat',
    title: 'Harris County Judge',
    bio: 'Harris County Judge since 2019, the top executive of Texas\'s and the nation\'s third-most populous county. One of the youngest county judges in Texas history, focused on flood control and criminal justice reform.',
    website_url: 'https://www.harriscountytx.gov/county-judge',
    image_url: null,
  },
  {
    name: 'Clay Lewis Jenkins',
    slug: 'clay-jenkins-dallas-tx',
    state: 'TX',
    chamber: 'county',
    party: 'democrat',
    title: 'Dallas County Judge',
    bio: 'Dallas County Judge since 2011, the top executive of the second-most-populous county in Texas. Attorney focused on public health, immigration, and social services.',
    website_url: 'https://www.dallascounty.org/government/county-judge/',
    image_url: null,
  },
  {
    name: 'Peter Sakai',
    slug: 'peter-sakai-bexar-tx',
    state: 'TX',
    chamber: 'county',
    party: 'democrat',
    title: 'Bexar County Judge',
    bio: 'Bexar County Judge since 2023, the top executive of the county that includes San Antonio. Former district judge focused on child welfare, public safety, and community health.',
    website_url: 'https://www.bexar.org/',
    image_url: null,
  },
  {
    name: 'Tim O\'Hare',
    slug: 'tim-ohare-tarrant-tx',
    state: 'TX',
    chamber: 'county',
    party: 'republican',
    title: 'Tarrant County Judge',
    bio: 'Tarrant County Judge since 2023, overseeing the county that includes Fort Worth. Former Farmers Branch mayor focused on fiscal conservatism and public safety.',
    website_url: 'https://www.tarrantcounty.com/',
    image_url: null,
  },
  {
    name: 'Andy Brown',
    slug: 'andy-brown-travis-tx',
    state: 'TX',
    chamber: 'county',
    party: 'democrat',
    title: 'Travis County Judge',
    bio: 'Travis County Judge since 2021, the top executive of the county that includes Austin. Former civil rights attorney focused on housing, transportation, and criminal justice reform.',
    website_url: 'https://www.traviscountytx.gov/',
    image_url: null,
  },
  // ── UTAH ──
  {
    name: 'Jenny Wilson',
    slug: 'jenny-wilson-salt-lake-ut',
    state: 'UT',
    chamber: 'county',
    party: 'democrat',
    title: 'Salt Lake County Mayor',
    bio: 'Salt Lake County Mayor since 2019, overseeing Utah\'s most populous county. Former county council member focused on air quality, homelessness, and regional planning.',
    website_url: 'https://slco.org/mayor/',
    image_url: null,
  },
  // ── VERMONT ──
  {
    name: 'Tom Sullivan',
    slug: 'tom-sullivan-chittenden-vt',
    state: 'VT',
    chamber: 'county',
    party: 'democrat',
    title: 'Chittenden County Senator/Official',
    bio: 'Vermont\'s most populous county, Chittenden County includes Burlington. Vermont does not have traditional county executives; governance is handled at state and municipal levels.',
    website_url: 'https://www.burlingtonvt.gov/',
    image_url: null,
  },
  // ── VIRGINIA ──
  {
    name: 'Jeff McKay',
    slug: 'jeff-mckay-fairfax-va',
    state: 'VA',
    chamber: 'county',
    party: 'democrat',
    title: 'Fairfax County Board of Supervisors Chairman',
    bio: 'Chairman of the Fairfax County Board of Supervisors since 2020, overseeing Virginia\'s most populous county and one of the wealthiest in the nation. Focused on education, transportation, and affordable housing.',
    website_url: 'https://www.fairfaxcounty.gov/chairman/',
    image_url: null,
  },
  {
    name: 'Christian Dorsey',
    slug: 'christian-dorsey-arlington-va',
    state: 'VA',
    chamber: 'county',
    party: 'democrat',
    title: 'Arlington County Board Chair',
    bio: 'Chair of the Arlington County Board, overseeing one of the smallest but most densely populated counties in the United States, directly across the Potomac from Washington, D.C.',
    website_url: 'https://www.arlingtonva.us/',
    image_url: null,
  },
  // ── WASHINGTON ──
  {
    name: 'Dow Constantine',
    slug: 'dow-constantine-expanded',
    state: 'WA',
    chamber: 'county',
    party: 'democrat',
    title: 'King County Executive',
    bio: 'King County Executive since 2009, overseeing the county that includes Seattle and the 13th-most populous county in the nation. Champion of regional transit, climate action, and equity.',
    website_url: 'https://kingcounty.gov/en/executive',
    image_url: null,
  },
  {
    name: 'Bruce Dammeier',
    slug: 'bruce-dammeier-pierce-wa',
    state: 'WA',
    chamber: 'county',
    party: 'republican',
    title: 'Pierce County Executive',
    bio: 'Pierce County Executive since 2017, overseeing the county that includes Tacoma. Former state legislator focused on public safety, fiscal responsibility, and human services.',
    website_url: 'https://www.piercecountywa.gov/',
    image_url: null,
  },
  {
    name: 'Dave Somers',
    slug: 'dave-somers-snohomish-wa',
    state: 'WA',
    chamber: 'county',
    party: 'democrat',
    title: 'Snohomish County Executive',
    bio: 'Snohomish County Executive since 2016, overseeing the county north of Seattle that includes Everett. Focused on economic development, public safety, and environmental stewardship.',
    website_url: 'https://snohomishcountywa.gov/',
    image_url: null,
  },
  // ── WEST VIRGINIA ──
  {
    name: 'Kent Carper',
    slug: 'kent-carper-kanawha-wv',
    state: 'WV',
    chamber: 'county',
    party: 'democrat',
    title: 'Kanawha County Commission President',
    bio: 'President of the Kanawha County Commission, overseeing West Virginia\'s most populous county which includes the capital city of Charleston.',
    website_url: 'https://www.kanawha.us/',
    image_url: null,
  },
  // ── WISCONSIN ──
  {
    name: 'David Crowley',
    slug: 'david-crowley-milwaukee-wi',
    state: 'WI',
    chamber: 'county',
    party: 'democrat',
    title: 'Milwaukee County Executive',
    bio: 'Milwaukee County Executive since 2020, the youngest person and first African American to serve as county executive. Focused on racial equity, public transit, and economic development.',
    website_url: 'https://county.milwaukee.gov/EN/County-Executive',
    image_url: null,
  },
  {
    name: 'Melissa Agard',
    slug: 'melissa-agard-dane-wi',
    state: 'WI',
    chamber: 'county',
    party: 'democrat',
    title: 'Dane County Executive',
    bio: 'Dane County Executive overseeing the county that includes Madison. Focused on climate action, housing, and government innovation in one of Wisconsin\'s fastest-growing counties.',
    website_url: 'https://www.countyofdane.com/',
    image_url: null,
  },
  // ── WYOMING ──
  {
    name: 'Pete Illoway',
    slug: 'pete-illoway-laramie-wy',
    state: 'WY',
    chamber: 'county',
    party: 'republican',
    title: 'Laramie County Commission Chair',
    bio: 'Chair of the Laramie County Board of Commissioners, overseeing Wyoming\'s most populous county which includes the capital city of Cheyenne.',
    website_url: 'https://www.laramiecounty.com/',
    image_url: null,
  },
]

console.log(`\nPreparing to upsert ${COUNTY_EXECUTIVES.length} county executives...\n`)

// Count by state
const stateCounts = {}
for (const p of COUNTY_EXECUTIVES) {
  stateCounts[p.state] = (stateCounts[p.state] || 0) + 1
}
const statesRepresented = Object.keys(stateCounts).length
console.log(`States represented: ${statesRepresented}`)
console.log(`By state:`, JSON.stringify(stateCounts, null, 2))

// Upsert in batches
const BATCH = 25
let inserted = 0
let errors = 0

for (let i = 0; i < COUNTY_EXECUTIVES.length; i += BATCH) {
  const batch = COUNTY_EXECUTIVES.slice(i, i + BATCH)
  const { data, error } = await supabase
    .from('politicians')
    .upsert(batch, { onConflict: 'slug' })
    .select('slug')

  if (error) {
    console.error(`  ✗ Batch ${Math.floor(i / BATCH) + 1} error:`, error.message)
    errors += batch.length
  } else {
    console.log(`  ✓ Batch ${Math.floor(i / BATCH) + 1}: ${data.length} rows upserted`)
    inserted += data.length
  }
}

console.log(`\nDone!`)
console.log(`  Upserted: ${inserted}`)
console.log(`  Errors:   ${errors}`)
console.log(`  Total:    ${COUNTY_EXECUTIVES.length} county executives from ${statesRepresented} states\n`)
