import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

const env = readFileSync('.env.local', 'utf8')
const vars = {}
for (const line of env.split('\n')) {
  const [k, ...v] = line.split('=')
  if (k && !k.startsWith('#')) vars[k.trim()] = v.join('=').trim()
}

const supabase = createClient(vars.NEXT_PUBLIC_SUPABASE_URL, vars.SUPABASE_SERVICE_ROLE_KEY)

// ─── DC Council (13 members) ───────────────────────────────────────────
const DC_COUNCIL = [
  {
    name: 'Phil Mendelson',
    slug: 'phil-mendelson',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Chairman, DC Council',
    bio: 'Chairman of the Council of the District of Columbia. Has served on the Council since 1998 and as Chairman since 2012. Oversees legislative operations for the District.',
    image_url: null,
  },
  {
    name: 'Anita Bonds',
    slug: 'anita-bonds',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'At-Large Councilmember, DC Council',
    bio: 'At-Large member of the DC Council. Longtime Democratic Party leader in the District, serving on the Council since 2012. Chairs the Committee on Housing.',
    image_url: null,
  },
  {
    name: 'Robert White',
    slug: 'robert-white-dc',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'At-Large Councilmember, DC Council',
    bio: 'At-Large member of the DC Council, first elected in 2016. Focuses on workforce development, education, and government accountability.',
    image_url: null,
  },
  {
    name: 'Christina Henderson',
    slug: 'christina-henderson',
    state: 'DC',
    chamber: 'city_council',
    party: 'independent',
    title: 'At-Large Councilmember, DC Council',
    bio: 'At-Large member of the DC Council, elected in 2020 as an Independent. Former Senate staffer focused on education and family policy.',
    image_url: null,
  },
  {
    name: 'Kenyan McDuffie',
    slug: 'kenyan-mcduffie',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'At-Large Councilmember, DC Council',
    bio: 'At-Large member of the DC Council. Previously represented Ward 5, now serves at-large. Attorney focused on public safety and economic development.',
    image_url: null,
  },
  {
    name: 'Brianne Nadeau',
    slug: 'brianne-nadeau',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 1 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 1 (Columbia Heights, Adams Morgan, Mount Pleasant). First elected in 2014. Focuses on housing affordability and public safety.',
    image_url: null,
  },
  {
    name: 'Brooke Pinto',
    slug: 'brooke-pinto',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 2 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 2 (Dupont Circle, Georgetown, Foggy Bottom). Won a 2020 special election. Chairs the Committee on the Judiciary and Public Safety.',
    image_url: null,
  },
  {
    name: 'Matthew Frumin',
    slug: 'matthew-frumin',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 3 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 3 (Tenleytown, Cleveland Park, Chevy Chase). Attorney and community advocate elected in 2022.',
    image_url: null,
  },
  {
    name: 'Janeese Lewis George',
    slug: 'janeese-lewis-george',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 4 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 4 (Petworth, Takoma, Brightwood). Civil rights attorney and progressive advocate elected in 2020.',
    image_url: null,
  },
  {
    name: 'Zachary Parker',
    slug: 'zachary-parker',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 5 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 5 (Brookland, Eckington, Trinidad). Former State Board of Education president, elected to Council in 2022.',
    image_url: null,
  },
  {
    name: 'Charles Allen',
    slug: 'charles-allen',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 6 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 6 (Capitol Hill, Navy Yard, Eastern Market). Elected in 2014, focuses on transportation, public safety, and criminal justice reform.',
    image_url: null,
  },
  {
    name: 'Vincent Gray',
    slug: 'vincent-gray',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 7 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 7. Former Mayor of Washington, D.C. (2011-2015). Long career in public service and human services leadership.',
    image_url: null,
  },
  {
    name: 'Trayon White',
    slug: 'trayon-white',
    state: 'DC',
    chamber: 'city_council',
    party: 'democrat',
    title: 'Ward 8 Councilmember, DC Council',
    bio: 'DC Council member representing Ward 8 (Anacostia, Congress Heights, Bellevue). Community organizer and youth mentor elected in 2016.',
    image_url: null,
  },
]

// ─── Puerto Rico Senate (27 members) ───────────────────────────────────
const PR_SENATE = [
  {
    name: 'Thomas Rivera Schatz',
    slug: 'thomas-rivera-schatz',
    state: 'PR',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator representing the Capitol District. Former President of the Puerto Rico Senate. Member of the New Progressive Party (PNP), affiliated with the Republican Party.',
    image_url: null,
  },
  {
    name: 'Jose Luis Dalmau Santiago',
    slug: 'jose-luis-dalmau-santiago',
    state: 'PR',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'President, Puerto Rico Senate',
    bio: 'President of the Puerto Rico Senate. Member of the Popular Democratic Party (PPD), affiliated with the Democratic Party. Represents the San Juan senatorial district.',
    image_url: null,
  },
  {
    name: 'Marially Gonzalez Huertas',
    slug: 'marially-gonzalez-huertas',
    state: 'PR',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Popular Democratic Party (PPD). Serves on committees focused on health and education.',
    image_url: null,
  },
  {
    name: 'Ruben Soto Rivera',
    slug: 'ruben-soto-rivera',
    state: 'PR',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Popular Democratic Party (PPD). Focuses on public safety and municipal affairs.',
    image_url: null,
  },
  {
    name: 'Ada Garcia Montes',
    slug: 'ada-garcia-montes',
    state: 'PR',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Popular Democratic Party (PPD). Advocates for women\'s rights and family services.',
    image_url: null,
  },
  {
    name: 'Gretchen Hau',
    slug: 'gretchen-hau',
    state: 'PR',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the New Progressive Party (PNP), affiliated with the Republican Party. Focuses on economic development.',
    image_url: null,
  },
  {
    name: 'Keren Riquelme',
    slug: 'keren-riquelme',
    state: 'PR',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the New Progressive Party (PNP), affiliated with the Republican Party.',
    image_url: null,
  },
  {
    name: 'Migdalia Padilla Alvelo',
    slug: 'migdalia-padilla-alvelo',
    state: 'PR',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the New Progressive Party (PNP), affiliated with the Republican Party. Veteran legislator focused on health policy.',
    image_url: null,
  },
  {
    name: 'William Villafane Ramos',
    slug: 'william-villafane-ramos',
    state: 'PR',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the New Progressive Party (PNP), affiliated with the Republican Party. Focuses on labor and economic issues.',
    image_url: null,
  },
  {
    name: 'Nitza Moran Trinidad',
    slug: 'nitza-moran-trinidad',
    state: 'PR',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the New Progressive Party (PNP), affiliated with the Republican Party.',
    image_url: null,
  },
  {
    name: 'Maria de Lourdes Santiago',
    slug: 'maria-de-lourdes-santiago',
    state: 'PR',
    chamber: 'state_senate',
    party: 'independent',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Puerto Rican Independence Party (PIP). Longtime advocate for Puerto Rican sovereignty and social justice.',
    image_url: null,
  },
  {
    name: 'Juan Zaragoza Gomez',
    slug: 'juan-zaragoza-gomez',
    state: 'PR',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Popular Democratic Party (PPD). Former Secretary of the Treasury of Puerto Rico.',
    image_url: null,
  },
  {
    name: 'Jose Vargas Vidot',
    slug: 'jose-vargas-vidot',
    state: 'PR',
    chamber: 'state_senate',
    party: 'independent',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator elected as an independent. Physician and humanitarian known for work with homeless populations.',
    image_url: null,
  },
  {
    name: 'Rafael Bernabe Riefkohl',
    slug: 'rafael-bernabe-riefkohl',
    state: 'PR',
    chamber: 'state_senate',
    party: 'independent',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Citizens\' Victory Movement (MVC). University professor, historian, and progressive political activist.',
    image_url: null,
  },
  {
    name: 'Ana Irma Rivera Lassen',
    slug: 'ana-irma-rivera-lassen',
    state: 'PR',
    chamber: 'state_senate',
    party: 'independent',
    title: 'Senator, Puerto Rico Senate',
    bio: 'Puerto Rico Senator. Member of the Citizens\' Victory Movement (MVC). Civil rights attorney and feminist activist.',
    image_url: null,
  },
]

// ─── Puerto Rico House of Representatives ──────────────────────────────
const PR_HOUSE = [
  {
    name: 'Rafael Hernandez Montanez',
    slug: 'rafael-hernandez-montanez',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Speaker, Puerto Rico House of Representatives',
    bio: 'Speaker of the Puerto Rico House of Representatives. Member of the Popular Democratic Party (PPD), affiliated with the Democratic Party.',
    image_url: null,
  },
  {
    name: 'Angel Matos Garcia',
    slug: 'angel-matos-garcia',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Majority Leader, Puerto Rico House',
    bio: 'Majority Leader of the Puerto Rico House of Representatives. Member of the Popular Democratic Party (PPD).',
    image_url: null,
  },
  {
    name: 'Jose Aponte Hernandez',
    slug: 'jose-aponte-hernandez',
    state: 'PR',
    chamber: 'state_house',
    party: 'republican',
    title: 'Minority Leader, Puerto Rico House',
    bio: 'Minority Leader of the Puerto Rico House. Member of the New Progressive Party (PNP), affiliated with the Republican Party. Veteran legislator.',
    image_url: null,
  },
  {
    name: 'Estrella Martinez Soto',
    slug: 'estrella-martinez-soto',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Focuses on education and community development.',
    image_url: null,
  },
  {
    name: 'Luis Raul Torres Cruz',
    slug: 'luis-raul-torres-cruz',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Works on infrastructure and transportation issues.',
    image_url: null,
  },
  {
    name: 'Lydia Mendez Silva',
    slug: 'lydia-mendez-silva',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Focuses on health and social services.',
    image_url: null,
  },
  {
    name: 'Jesus Manuel Ortiz Gonzalez',
    slug: 'jesus-manuel-ortiz-gonzalez',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Serves as Vice President of the PPD.',
    image_url: null,
  },
  {
    name: 'Denis Marquez Lemus',
    slug: 'denis-marquez-lemus',
    state: 'PR',
    chamber: 'state_house',
    party: 'independent',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Puerto Rican Independence Party (PIP). Advocates for Puerto Rican sovereignty.',
    image_url: null,
  },
  {
    name: 'Mariana Nogales Molinelli',
    slug: 'mariana-nogales-molinelli',
    state: 'PR',
    chamber: 'state_house',
    party: 'independent',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Citizens\' Victory Movement (MVC). Environmental attorney and progressive activist.',
    image_url: null,
  },
  {
    name: 'Joel Franqui Atiles',
    slug: 'joel-franqui-atiles',
    state: 'PR',
    chamber: 'state_house',
    party: 'republican',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. New Progressive Party (PNP), affiliated with the Republican Party.',
    image_url: null,
  },
  {
    name: 'Lourdes Ramos Rivera',
    slug: 'lourdes-ramos-rivera',
    state: 'PR',
    chamber: 'state_house',
    party: 'republican',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. New Progressive Party (PNP), affiliated with the Republican Party. Former Secretary of Corrections.',
    image_url: null,
  },
  {
    name: 'Gabriel Rodriguez Aguilo',
    slug: 'gabriel-rodriguez-aguilo',
    state: 'PR',
    chamber: 'state_house',
    party: 'republican',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. New Progressive Party (PNP), affiliated with the Republican Party.',
    image_url: null,
  },
  {
    name: 'Jose Rivera Madera',
    slug: 'jose-rivera-madera',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Works on agricultural and rural development issues.',
    image_url: null,
  },
  {
    name: 'Deborah Soto Arroyo',
    slug: 'deborah-soto-arroyo',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Focuses on women\'s issues and public safety.',
    image_url: null,
  },
  {
    name: 'Edgardo Feliciano Sanchez',
    slug: 'edgardo-feliciano-sanchez',
    state: 'PR',
    chamber: 'state_house',
    party: 'democrat',
    title: 'Representative, Puerto Rico House',
    bio: 'Member of the Puerto Rico House of Representatives. Popular Democratic Party (PPD). Works on labor and economic development.',
    image_url: null,
  },
]

// ─── Guam Legislature (15 senators, unicameral) ────────────────────────
const GUAM_LEGISLATURE = [
  {
    name: 'Therese Terlaje',
    slug: 'therese-terlaje',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Speaker, Guam Legislature',
    bio: 'Speaker of the 37th Guam Legislature. Attorney and longtime public servant focused on indigenous Chamorro rights, health care, and environmental protection.',
    image_url: null,
  },
  {
    name: 'Tina Muna Barnes',
    slug: 'tina-muna-barnes',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Former Speaker of the Guam Legislature. Experienced lawmaker focused on labor and public safety issues.',
    image_url: null,
  },
  {
    name: 'Jose Terlaje',
    slug: 'jose-terlaje',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Focuses on public health, veterans affairs, and community development.',
    image_url: null,
  },
  {
    name: 'Sabina Perez',
    slug: 'sabina-perez',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Environmental advocate and progressive lawmaker. First openly LGBTQ senator elected in Guam.',
    image_url: null,
  },
  {
    name: 'Chris Duenas',
    slug: 'chris-duenas',
    state: 'GU',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Republican lawmaker focused on fiscal responsibility and economic development.',
    image_url: null,
  },
  {
    name: 'Frank Blas Jr',
    slug: 'frank-blas-jr',
    state: 'GU',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Republican lawmaker and former Vice Speaker. Focuses on public safety and justice reform.',
    image_url: null,
  },
  {
    name: 'Joanne Brown',
    slug: 'joanne-brown-gu',
    state: 'GU',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Republican lawmaker focused on military affairs and veterans\' issues.',
    image_url: null,
  },
  {
    name: 'Roy Quinata',
    slug: 'roy-quinata',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Focuses on education, health, and community welfare.',
    image_url: null,
  },
  {
    name: 'Dwayne San Nicolas',
    slug: 'dwayne-san-nicolas',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Focuses on infrastructure, transportation, and economic development.',
    image_url: null,
  },
  {
    name: 'Thomas Fisher',
    slug: 'thomas-fisher-gu',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Works on public health, education, and social services.',
    image_url: null,
  },
  {
    name: 'Darren Matanane',
    slug: 'darren-matanane',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Focuses on government reform and fiscal accountability.',
    image_url: null,
  },
  {
    name: 'William Parkinson',
    slug: 'william-parkinson',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Works on public utilities, land, and environmental issues.',
    image_url: null,
  },
  {
    name: 'Jesse Lujan',
    slug: 'jesse-lujan',
    state: 'GU',
    chamber: 'state_senate',
    party: 'republican',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Republican lawmaker focused on tourism, economic growth, and public safety.',
    image_url: null,
  },
  {
    name: 'Joe San Agustin',
    slug: 'joe-san-agustin',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Retired military officer focused on veterans affairs and public safety.',
    image_url: null,
  },
  {
    name: 'Chris Barnett',
    slug: 'chris-barnett',
    state: 'GU',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Guam Legislature',
    bio: 'Senator in the Guam Legislature. Former radio personality turned lawmaker. Focuses on government transparency and constituent services.',
    image_url: null,
  },
]

// ─── US Virgin Islands Legislature (15 senators, unicameral) ───────────
const VI_LEGISLATURE = [
  {
    name: 'Donna Frett-Gregory',
    slug: 'donna-frett-gregory',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'President, Virgin Islands Legislature',
    bio: 'President of the Legislature of the US Virgin Islands. Represents the St. Thomas-St. John District. Focuses on economic development and fiscal responsibility.',
    image_url: null,
  },
  {
    name: 'Novelle Francis Jr',
    slug: 'novelle-francis-jr',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Vice President, Virgin Islands Legislature',
    bio: 'Vice President of the Legislature of the US Virgin Islands. Represents the St. Croix District.',
    image_url: null,
  },
  {
    name: 'Milton Potter',
    slug: 'milton-potter',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Thomas-St. John District. Businessman and community leader.',
    image_url: null,
  },
  {
    name: 'Marvin Blyden',
    slug: 'marvin-blyden',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Thomas-St. John District. Focuses on labor, public works, and veterans affairs.',
    image_url: null,
  },
  {
    name: 'Alma Francis Heyliger',
    slug: 'alma-francis-heyliger',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Thomas-St. John District. Advocates for education and youth development.',
    image_url: null,
  },
  {
    name: 'Dwayne DeGraff',
    slug: 'dwayne-degraff',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Thomas-St. John District. Focuses on housing and community development.',
    image_url: null,
  },
  {
    name: 'Kenneth Gittens',
    slug: 'kenneth-gittens',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Former Senate President. Focuses on public safety and health.',
    image_url: null,
  },
  {
    name: 'Samuel Carrion',
    slug: 'samuel-carrion',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Works on education and workforce development.',
    image_url: null,
  },
  {
    name: 'Franklin Johnson',
    slug: 'franklin-johnson',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Focuses on agriculture and economic diversification.',
    image_url: null,
  },
  {
    name: 'Carla Joseph',
    slug: 'carla-joseph-vi',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Advocates for women\'s rights and social services.',
    image_url: null,
  },
  {
    name: 'Javan James Sr',
    slug: 'javan-james-sr',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Thomas-St. John District. Community advocate and public servant.',
    image_url: null,
  },
  {
    name: 'Marise James',
    slug: 'marise-james',
    state: 'VI',
    chamber: 'state_senate',
    party: 'independent',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Independent lawmaker focused on government accountability.',
    image_url: null,
  },
  {
    name: 'Ray Fonseca',
    slug: 'ray-fonseca',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Works on environmental protection and natural resources.',
    image_url: null,
  },
  {
    name: 'Angel Bolques Jr',
    slug: 'angel-bolques-jr',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing the St. Croix District. Focuses on youth services and community development.',
    image_url: null,
  },
  {
    name: 'Diane Capehart',
    slug: 'diane-capehart',
    state: 'VI',
    chamber: 'state_senate',
    party: 'democrat',
    title: 'Senator, Virgin Islands Legislature',
    bio: 'Senator in the US Virgin Islands Legislature representing At-Large. Attorney and community advocate focused on judicial reform.',
    image_url: null,
  },
]

// ─── Combine and upsert ────────────────────────────────────────────────
const ALL = [
  ...DC_COUNCIL,
  ...PR_SENATE,
  ...PR_HOUSE,
  ...GUAM_LEGISLATURE,
  ...VI_LEGISLATURE,
]

console.log(`Upserting ${ALL.length} officials from DC and US territories...`)
console.log(`  DC Council: ${DC_COUNCIL.length}`)
console.log(`  PR Senate: ${PR_SENATE.length}`)
console.log(`  PR House: ${PR_HOUSE.length}`)
console.log(`  Guam Legislature: ${GUAM_LEGISLATURE.length}`)
console.log(`  VI Legislature: ${VI_LEGISLATURE.length}`)

// Upsert in batches of 50
const BATCH = 50
let inserted = 0
for (let i = 0; i < ALL.length; i += BATCH) {
  const batch = ALL.slice(i, i + BATCH)
  const { data, error } = await supabase
    .from('politicians')
    .upsert(batch, { onConflict: 'slug' })
    .select('id')

  if (error) {
    console.error(`Error at batch ${i}:`, error.message)
    process.exit(1)
  }
  inserted += data.length
  console.log(`  Batch ${Math.floor(i / BATCH) + 1}: ${data.length} rows`)
}

console.log(`Done. ${inserted} officials upserted.`)
